services:
  db:
    ports:
      - "5434:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    container_name: ocomme_dev_server
    volumes:
      - ../../src/backend/ocomme:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    entrypoint: []
    ports:
      - "8000:8000"
    command: sleep infinity
    deploy:
      resources:
        limits:
          cpus: "4.0"    # Tăng lên 4 nhân hoặc hơn tùy máy bạn
          memory: 4G

  celery:
    container_name: ocomme_dev_celery
    volumes:
      - ../../src/backend/ocomme:/app
    environment:
      - DEBUG=True
    command: >
      watchfiles --filter python
      "celery -A config worker -l info"

  celery-beat:
    container_name: ocomme_dev_beat
    volumes:
      - ../../src/backend/ocomme:/app
    command: celery -A config beat -l info

volumes:
  static_volume:
  media_volume: