services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  web:
    container_name: ocomme_dev_server
    volumes:
      - ../../src/backend/ocomme:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    container_name: ocomme_dev_celery
    volumes:
      - ../../src/backend/ocomme:/app
    environment:
      - DEBUG=True
    command: >
      watchfiles --filter python
      "celery -A config worker -l info"

  celery-beat:
    container_name: ocomme_dev_beat
    volumes:
      - ../../src/backend/ocomme:/app
    command: celery -A config beat -l info

volumes:
  static_volume:
  media_volume: