# Generated by Django 5.1.15 on 2026-03-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_merchant_failed_login_attempts_merchant_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='name',
            field=models.CharField(blank=True, max_length=208, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
