# Generated by Django 5.1.15 on 2026-03-24 08:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_merchant_name_merchant_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
